name: Package Application with Pyinstaller

on:
  push

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - name: hello, world
      run: echo "Hello, World"
    
    - uses: actions/checkout@v2

    - name: Package Application
      run: |
        pip install -r src/requirements.txt
        pip install pyinstaller
        pyinstaller -F --clean -y --dist $GITHUB_WORKSPACE/main src/main.py
        zip $GITHUB_WORKSPACE/main.zip $GITHUB_WORKSPACE/main/main
        
    - uses: actions/upload-artifact@v1
      with:
        name: main.zip
        path: main.zip
      name: 'Upload Package'

