name: Package Application with Pyinstaller

on:
  push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      run: |
        pip install -r src/requirements.txt
        pip install pyinstaller

    - uses: actions/upload-artifact@v2
      with:
        name: name-of-artifact
        path: src/dist/linux
